[build-system]
requires = ["setuptools>=61", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "mooi-toolbox"
dynamic = ["version"]

[tool.setuptools_scm]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.scripts]
crane_convert_to_bids = "mooi_toolbox.cli.crane_convert_to_bids:main"
crane_generate_sample_data = "mooi_toolbox.cli.crane_generate_sample_data:main"
mobi_check_xdf = "mooi_toolbox.cli.check_mobi_xdf:main"
mobi_foh_assess_data = "mooi_toolbox.cli.mobi_FOH_assess_data:main"
mobi_foh_bids_crosscheck = "mooi_toolbox.gui.foh_bids_crosscheck_gui:main"
mobi_foh_process = "mooi_toolbox.cli.mobi_FOH_process:main"
mobi_foh_batch_process = "mooi_toolbox.cli.mobi_FOH_process_batch:main"
plot_target_data = "mooi_toolbox.cli.plot_subject_target_scr_bars:main"
vrlab_crane_bids_crosscheck = "mooi_toolbox.gui.crane_bids_crosscheck_gui:main"
vrlab_crane_process = "mooi_toolbox.cli.vrlab_crane_process:main"
vrlab_crane_summary_data = "mooi_toolbox.cli.vrlab_crane_qc:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.mooi_toolbox]
default_path = "local_lsl_data" #CurrentStudy folder
default_xdf_folder = "eeg"
default_session = "001"
default_xdf_task = "Default"
default_subject = "P00018"
eda_opensignals_data_label = "EDA0"
eda_biopac_data_label = "EDA"

[tool.mooi_toolbox.trial_intervals.baseline]
start = { stream = "VR_markers", column = "Markers", event = 10 }
start_fallback = { stream = "VR_trial_events", column = "VR_trial", event = "RaiseSafetyPlatform", offset_seconds = -300 }
end = { stream = "VR_trial_events", column = "VR_trial", event = "RaiseSafetyPlatform" }

[tool.mooi_toolbox.trial_intervals.stress]
start = { stream = "VR_trial_events", column = "VR_trial", event = "RaiseMainPlatform" }
end = { stream = "VR_trial_events", column = "VR_trial", event = "MainPlatformAtMin" }

[tool.mooi_toolbox.trial_intervals.recovery]
start = { stream = "VR_trial_events", column = "VR_trial", event = "MainPlatformAtMin" }
end = { stream = "VR_trial_events", column = "VR_trial", event = "RunFOHQuestions" }

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"