import logging
import tempfile
import unittest
from pathlib import Path

import matplotlib
import numpy as np
from click.testing import CliRunner

from vrlab_toolbox.cli.vrlab_crane_process import main as run_batch

matplotlib.use("Agg")
from vrlab_toolbox.processing.biodata import RawBioData
from vrlab_toolbox.processing.biopac import BiopacPhysiologyDataImportStartegy
from vrlab_toolbox.processing.crane_behaviour import (
    ImportCraneBehaviourDataStrategyStep,
    ProcessCraneBehaviourDataStrategyStep,
    RawCraneBehaviourData,
    build_crane_raw_behav_file_schema,
)
from vrlab_toolbox.processing.crane_bids import convert_crane_to_bids
from vrlab_toolbox.processing.crane_debrief_behaviour import RawDebriefBehaviourData
from vrlab_toolbox.processing.crane_dummy_data import (
    discover_template_pairs,
    generate_dummy_debrief_workbook,
    generate_dummy_participant,
)
from vrlab_toolbox.processing.crane_pipeline import (
    FindCraneParticipantFilesStrategyStep,
    run_pipeline,
)
from vrlab_toolbox.processing.crane_trial_intervals import CraneGetTrialIntervalStrategyStep
from vrlab_toolbox.processing.input_data import ParticipantConfig
from vrlab_toolbox.processing.processing_status import PipelineStatus, ProcessingStatus
from vrlab_toolbox.processing.trial_intervals import TrialIntervals

# Real, gitignored data used only by the "real data" tests below -- those fail on any machine
# without this folder present, by design (no synthetic equivalent exists yet for these PIDs).
REAL_DATA_BIDS_FOLDER = Path(r"crane_data\crane_bids")

# BIDS-shaped output of crane_generate_sample_data + crane_convert_to_bids (see
# crane_examples/crane_bids_dummy/dummy_data_log.txt) -- sub-XXX/ses-01/beh/... BIDS layout.
# Regenerate with: crane_generate_sample_data crane_examples/crane_templates crane_examples
# --with-errors --seed 42 --bids-folder crane_examples/crane_bids_dummy (see docs/testing.md).
EXAMPLES_FOLDER = Path(r"crane_examples\\crane_bids_dummy")

CRANE_PARTICIPANT_NO_FILE_ID = "NOFILES"
EXAMPLE_LONG_DELAY_ID = "00011"
EXAMPLE_INCORRECT_MEDIUM_SHORT_TRIGGER_ID = "PID16407"

# Dummy data generated by crane_dummy_data.generate_dummy_dataset(), one clean ID
# plus one ID per ERROR_TYPES scenario it knows how to reproduce.
DUMMY_CLEAN_ID = "DUMMY000"
DUMMY_MISSING_PHYSIOLOGY_ID = "DUMMY005"
DUMMY_MISSING_BEHAVIOUR_ID = "DUMMY006"
DUMMY_MISSING_DEBRIEF_ID = "DUMMY007"
DUMMY_BAD_TRIGGER_COUNT_ID = "DUMMY008"
DUMMY_SHORT_TRIGGER_ID = "DUMMY009"

ALL_OK_STATUS_STR = PipelineStatus(
    status={
        RawCraneBehaviourData: ProcessingStatus.OK,
        RawDebriefBehaviourData: ProcessingStatus.OK,
        RawBioData: ProcessingStatus.OK,
        TrialIntervals: ProcessingStatus.OK,
    }
).get_as_text()

CORRECTED_INTERVAL_STATUS_STR = PipelineStatus(
    status={
        RawCraneBehaviourData: ProcessingStatus.OK,
        RawDebriefBehaviourData: ProcessingStatus.OK,
        RawBioData: ProcessingStatus.OK,
        TrialIntervals: ProcessingStatus.ERROR,
    }
).get_as_text()

MISSING_DEBRIEF_STATUS_STR = PipelineStatus(
    status={
        RawCraneBehaviourData: ProcessingStatus.OK,
        RawDebriefBehaviourData: ProcessingStatus.ERROR,
        RawBioData: ProcessingStatus.OK,
        TrialIntervals: ProcessingStatus.OK,
    }
).get_as_text()


# ---------------------------------------------------------------------------
# Individual strategy steps (import, behaviour processing)
# ---------------------------------------------------------------------------


class TestBasicDataHandling(unittest.TestCase):
    def test_find_crane_participant_strategy(self):
        good_config = FindCraneParticipantFilesStrategyStep().run(DUMMY_CLEAN_ID, EXAMPLES_FOLDER)
        no_file_config = FindCraneParticipantFilesStrategyStep().run(
            CRANE_PARTICIPANT_NO_FILE_ID, EXAMPLES_FOLDER
        )
        self.assertIsInstance(good_config, ParticipantConfig)
        self.assertIsInstance(no_file_config, ParticipantConfig)

    def setUp(self):
        self.good_config = FindCraneParticipantFilesStrategyStep().run(
            DUMMY_CLEAN_ID, EXAMPLES_FOLDER
        )
        self.no_file_config = FindCraneParticipantFilesStrategyStep().run(
            CRANE_PARTICIPANT_NO_FILE_ID, EXAMPLES_FOLDER
        )

    def test_good_raw_data_init_should_return_ok(self):
        raw_biodata = BiopacPhysiologyDataImportStartegy().run(self.good_config)
        self.assertIsInstance(raw_biodata, RawBioData)

    def test_no_data_should_return_error(self):
        with self.assertRaises(FileNotFoundError):
            BiopacPhysiologyDataImportStartegy().run(self.no_file_config)


class TestCraneBehaviourStrategy(unittest.TestCase):
    def setUp(self):
        self.config = FindCraneParticipantFilesStrategyStep().run(DUMMY_CLEAN_ID, EXAMPLES_FOLDER)

    def test_bids_behav_import(self):
        raw_behaviour = ImportCraneBehaviourDataStrategyStep().run(self.config)
        build_crane_raw_behav_file_schema().validate(raw_behaviour.raw_behav_df)

    def test_crane_process_behaviour(self):
        raw_behaviour = ImportCraneBehaviourDataStrategyStep().run(config_in=self.config)
        processed = ProcessCraneBehaviourDataStrategyStep().run(self.config, raw_behaviour)
        self.assertEqual(processed.subject_df_out["Subject_ID"].iloc[0], DUMMY_CLEAN_ID)


# ---------------------------------------------------------------------------
# Full pipeline -- dummy data (self-contained, run anywhere)
# ---------------------------------------------------------------------------


class TestCranePipelineDummyData(unittest.TestCase):
    def test_crane_pipeline_has_expected_output(self):
        pipeline_out = run_pipeline(DUMMY_CLEAN_ID, EXAMPLES_FOLDER)
        pipeline_out.validate_participant_output()
        status_str = pipeline_out.subject_df_out["Processing_Status"].iloc[0]
        self.assertEqual(sorted(status_str.split(" ")), sorted(ALL_OK_STATUS_STR.split(" ")))

    def test_crane_pipeline_labels_missing_physiology_correctly(self):
        pipeline_out = run_pipeline(DUMMY_MISSING_PHYSIOLOGY_ID, EXAMPLES_FOLDER)
        self.assertEqual(pipeline_out.status.status[RawBioData], ProcessingStatus.ERROR)

    def test_crane_pipeline_labels_missing_behav_correctly(self):
        pipeline_out = run_pipeline(DUMMY_MISSING_BEHAVIOUR_ID, EXAMPLES_FOLDER)
        self.assertEqual(pipeline_out.status.status[RawCraneBehaviourData], ProcessingStatus.ERROR)

    def test_crane_missing_debrief_correct_label(self):
        pipeline_out = run_pipeline(DUMMY_MISSING_DEBRIEF_ID, EXAMPLES_FOLDER)
        self.assertEqual(
            pipeline_out.status.status[RawDebriefBehaviourData], ProcessingStatus.ERROR
        )
        status_str = pipeline_out.subject_df_out["Processing_Status"].iloc[0]
        self.assertEqual(
            sorted(status_str.split(" ")), sorted(MISSING_DEBRIEF_STATUS_STR.split(" "))
        )

    def test_crane_corrects_error_for_incorrect_interval_nr(self):
        pipeline_out = run_pipeline(DUMMY_BAD_TRIGGER_COUNT_ID, EXAMPLES_FOLDER)
        self.assertEqual(pipeline_out.status.status[TrialIntervals], ProcessingStatus.ERROR)
        status_str = pipeline_out.subject_df_out["Processing_Status"].iloc[0]
        self.assertEqual(
            sorted(status_str.split(" ")), sorted(CORRECTED_INTERVAL_STATUS_STR.split(" "))
        )

    def test_crane_returns_ok_for_correct_interval_nr(self):
        pipeline_out = run_pipeline(DUMMY_CLEAN_ID, EXAMPLES_FOLDER)
        self.assertEqual(pipeline_out.status.status[TrialIntervals], ProcessingStatus.OK)
        status_str = pipeline_out.subject_df_out["Processing_Status"].iloc[0]
        self.assertEqual(sorted(status_str.split(" ")), sorted(ALL_OK_STATUS_STR.split(" ")))

    def test_crane_handles_very_short_triggers(self):
        # The short-trigger interval mismatch leaves no EDA intervals to concatenate, so
        # RawBioData ends up PARTIAL rather than OK, unlike bad_trigger_count.
        short_trigger_status_str = PipelineStatus(
            status={
                RawCraneBehaviourData: ProcessingStatus.OK,
                RawDebriefBehaviourData: ProcessingStatus.OK,
                RawBioData: ProcessingStatus.PARTIAL,
                TrialIntervals: ProcessingStatus.ERROR,
            }
        ).get_as_text()

        pipeline_out = run_pipeline(DUMMY_SHORT_TRIGGER_ID, EXAMPLES_FOLDER)
        self.assertEqual(pipeline_out.status.status[TrialIntervals], ProcessingStatus.ERROR)
        status_str = pipeline_out.subject_df_out["Processing_Status"].iloc[0]
        self.assertEqual(sorted(status_str.split(" ")), sorted(short_trigger_status_str.split(" ")))

    def test_crane_flags_unbalanced_trial_conditions_without_crashing(self):
        # Regression test: build_crane_raw_behav_file_schema's balanced_block_trial_conditions
        # check raises pandera.errors.SchemaError, which used to escape
        # SequentialBehaviourImportSteps.run() untouched and crash the whole batch (see the
        # except tuples in pipeline.py). Generated fresh via crane_dummy_data rather than added
        # to EXAMPLES_FOLDER's committed BIDS fixtures.
        with tempfile.TemporaryDirectory() as raw_dir, tempfile.TemporaryDirectory() as bids_dir:
            raw_folder = Path(raw_dir)
            bids_folder = Path(bids_dir)
            csv_template, mat_template = discover_template_pairs(
                Path("crane_examples/crane_templates")
            )[0]
            subject_id = "DUMMYUNBAL"

            _, debrief_rows = generate_dummy_participant(
                csv_template,
                mat_template,
                subject_id,
                "2026900",
                "2026900",
                raw_folder,
                np.random.default_rng(0),
                error_type="unbalanced_trial_conditions",
            )
            generate_dummy_debrief_workbook([debrief_rows], raw_folder)
            convert_crane_to_bids(raw_folder, bids_folder)

            pipeline_out = run_pipeline(subject_id, bids_folder)

            self.assertEqual(
                pipeline_out.status.status[RawCraneBehaviourData], ProcessingStatus.ERROR
            )

    def test_batch_processing(self):
        # This project's pytest config sets log_cli=true, which conflicts with click's
        # CliRunner stdout capture: any logger call during invoke() crashes with "ValueError:
        # I/O operation on closed file" (see the same fix in test_longwalk.py's
        # TestLongwalkConvertToBidsCli.setUp). Disabling logging around invoke() sidesteps it.
        logging.disable(logging.CRITICAL)
        try:
            with tempfile.TemporaryDirectory() as output_folder:
                result = CliRunner().invoke(run_batch, [str(EXAMPLES_FOLDER), output_folder])
        finally:
            logging.disable(logging.NOTSET)
        self.assertEqual(result.exit_code, 0, msg=result.output)


# ---------------------------------------------------------------------------
# Interval correction and full pipeline -- real data (needs REAL_DATA_BIDS_FOLDER
# on disk). Grouped last, same split as test_longwalk.py/test_foh_pipeline.py: everything
# self-contained above, everything needing real, gitignored data below. One test per real,
# recorded trigger anomaly -- no dummy equivalent exists for these yet.
# ---------------------------------------------------------------------------


class TestCraneGetIntervalStrategy(unittest.TestCase):
    def _run_interval_strategy_for(
        self, subject_id: str, folder: Path = REAL_DATA_BIDS_FOLDER
    ) -> TrialIntervals:
        participant_config = FindCraneParticipantFilesStrategyStep().run(subject_id, folder)
        raw_bio_data = BiopacPhysiologyDataImportStartegy().run(participant_config)
        raw_behav_data = ImportCraneBehaviourDataStrategyStep().run(participant_config)
        trial_intervals, _, status = CraneGetTrialIntervalStrategyStep().run(
            raw_bio_data, raw_behav_data
        )
        print(subject_id, status)
        return trial_intervals

    def test_interval_correction_with_correct_intervals(self):
        self.assertTrue(self._run_interval_strategy_for(DUMMY_CLEAN_ID, EXAMPLES_FOLDER).intervals)

    def test_interval_correction_with_missing_initial_trigger_tp(self):
        MISSING_INITIAL_TRIGGER = "PID16186"
        self.assertTrue(self._run_interval_strategy_for(MISSING_INITIAL_TRIGGER).intervals)

    def test_interval_correction_with_initial_double_trigger(self):
        INITIAL_DOUBLE_TRIGGER = "PID16407"
        self.assertTrue(self._run_interval_strategy_for(INITIAL_DOUBLE_TRIGGER).intervals)

    def test_interval_correction_with_double_trigger_and_missing_init_tp_nr1(self):
        MISSING_TRIGGER_AND_INIT_TP_1 = "PID5753"
        self.assertTrue(self._run_interval_strategy_for(MISSING_TRIGGER_AND_INIT_TP_1).intervals)

    def test_shifting_algorithm_for_missing_first_last_tp(self):
        MISSING_INIT_AND_LAST_TP = "PID1267"
        self.assertTrue(self._run_interval_strategy_for(MISSING_INIT_AND_LAST_TP).intervals)

    def test_interval_correction_with_double_trigger_and_missing_init_tp_nr2(self):
        MISSING_TRIGGER_AND_INIT_TP_2 = "PID4572"
        self.assertTrue(self._run_interval_strategy_for(MISSING_TRIGGER_AND_INIT_TP_2).intervals)

    def test_interval_correction_with_missing_last_and_initial_triggers(self):
        MISSING_LAST_AND_INITIAL_TRIGGERS = "PID16230"
        self.assertTrue(
            self._run_interval_strategy_for(MISSING_LAST_AND_INITIAL_TRIGGERS).intervals
        )

    @unittest.skip("Double triggers beyond scope for now.")
    def test_interval_correction_with_multiple_double_triggers_1(self):
        MULTIPLE_DOUBLE_TRIGGERS_1 = "PID9188"
        self.assertTrue(self._run_interval_strategy_for(MULTIPLE_DOUBLE_TRIGGERS_1).intervals)

    @unittest.skip("Double triggers beyond scope for now.")
    def test_interval_correction_with_multiple_double_triggers_2(self):
        MULTIPLE_DOUBLE_TRIGGERS_2 = "PID7177"  # worse!
        self.assertTrue(self._run_interval_strategy_for(MULTIPLE_DOUBLE_TRIGGERS_2).intervals)


class TestCranePipelineRealData(unittest.TestCase):
    def test_crane_handles_long_delay_time(self):
        """Currently no error with excessive delays"""
        pipeline_out = run_pipeline(EXAMPLE_LONG_DELAY_ID, REAL_DATA_BIDS_FOLDER)
        self.assertEqual(pipeline_out.status.status[TrialIntervals], ProcessingStatus.OK)
        status_str = pipeline_out.subject_df_out["Processing_Status"].iloc[0]
        self.assertEqual(sorted(status_str.split(" ")), sorted(ALL_OK_STATUS_STR.split(" ")))

    def test_crane_handles_medium_short_triggers(self):
        # Also has missing debrief; RawCraneBehaviourData shows ERROR too -- see the note on
        # MISSING_DEBRIEF_STATUS_STR above re: the SequentialBehaviourImportSteps.run() artifact.
        corrected_interval_str = PipelineStatus(
            status={
                RawCraneBehaviourData: ProcessingStatus.OK,
                RawDebriefBehaviourData: ProcessingStatus.ERROR,
                RawBioData: ProcessingStatus.OK,
                TrialIntervals: ProcessingStatus.ERROR,
            }
        ).get_as_text()

        pipeline_out = run_pipeline(
            EXAMPLE_INCORRECT_MEDIUM_SHORT_TRIGGER_ID, REAL_DATA_BIDS_FOLDER
        )
        self.assertEqual(pipeline_out.status.status[TrialIntervals], ProcessingStatus.ERROR)
        status_str = pipeline_out.subject_df_out["Processing_Status"].iloc[0]
        self.assertEqual(sorted(status_str.split(" ")), sorted(corrected_interval_str.split(" ")))


if __name__ == "__main__":
    unittest.main()
